# uplift.yaml
# see https://upliftci.dev/
bumps:
  - file: main.go
    regex:
      - pattern: 'const APP_VERSION = "$VERSION"'
        semver: false
annotatedTags: true
changelog:
  exclude:
    - "chore"
    - "refactor"
    - "style"
    - "test"
    - "wip"
commitMessage: "chore(release): $VERSION"
